### ISSUE TITLE
Processing natural language into existing commands

### ISSUE THREAD

**Issue by chweeee** [CS2103JAN2018-W09-B3/main#24]
**TODO**

- [x] 1.  Implement basic functionality
- [ ] 2.  Able to parse commands
- [ ] 3.  Add tests
- [ ] 4.  support new commands that will be introduced up till V1.5
- [ ] 5.  Update UG and DG

**Motivation**
The command box is going to be the main way for the user to navigate through EducateBook.
It would be ideal if the user is able to execute their desired commands without conforming to the pre-defined syntax specific to each command, using free-form English.

**Description**
By using IBM Watson Assistant API , entities that correspond to the commands and perimeters are extracted from the user input and re-packaged to be parsed by the pre-built existing commands. Only the logic component is involved in this process.
